### PR TITLE
Update content and fix values slide

### PR DESCRIPTION
**Pull request by v-hal**
Sorry about the indentation changes. That's my formatter.

- The values -slide had some issues. I fixed it by using titles. Hope that's okay. 
- Changed all the bullet points to start with a capital letter for consistency. 
- Fixed some typos
- Updated my skills :D

### CODE REVIEW

**Comment by undefinedTea** [comment]
Case corrections and typo fixes are good, so is the update to your skills ^^
The indentation changes are unfortunate, but it's my bad for not including an `.editorconfig` so those are fine for now as well.

the css change however should be moved to `reveal/css/theme/source/hacktober.scss` to be sure they are not removed the next time i build the project files.

**Comment by v-hal** [comment]
Good point. I didn't notice that it gets built from scss.

**Comment by undefinedTea** [comment]
yea, also my bad for no readme :/

**Comment by v-hal** [comment]
Moved the style to .scss.

**Comment by undefinedTea** [comment]
:S sorry to make this more complex than it has to be, but you made the change in the `presentation.scss` file, which is a separate theme from the `hacktober.scss` one. unless this issue concern both themes, it should be moved to the `hacktober.scss` source file - and if it concerns both or rather all themes it could be moved to the global `reveal/css/theme/template/settings.scss` file.

**Comment by undefinedTea** [comment]
thx Ville

**Pull request merged**
